# Generated by Django 5.1.6 on 2025-02-24 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("usertask", "0003_addtask_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="addtask",
            name="deleted",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="addtask",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="addtask",
            name="status",
            field=models.IntegerField(
                choices=[(1, "Pending"), (2, "Completed")], default=1
            ),
        ),
    ]
