# Generated by Django 5.1.6 on 2025-02-24 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("usertask", "0004_addtask_deleted_alter_addtask_created_at_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="addtask",
            name="status",
            field=models.BooleanField(default=False),
        ),
    ]
