# Generated by Django 5.1.6 on 2025-02-24 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("usertask", "0005_alter_addtask_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="addtask",
            name="status",
            field=models.IntegerField(
                choices=[(1, "Pending"), (2, "Completed")], default=1
            ),
        ),
    ]
