# Generated by Django 5.1.6 on 2025-02-25 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("usertask", "0006_alter_addtask_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="addtask",
            name="status",
            field=models.BooleanField(default=False),
        ),
    ]
